export type Locale = "en" | "ko";
const ko: Record<string,string> = {
"Overview":"개요","Stocks":"종목","Models":"모델","Evidence":"근거 자료","Backtesting":"백테스트","Mock research data":"모의 연구 데이터",
"Research dashboard":"연구 대시보드","Research readiness":"연구 준비 상태","Historical run":"과거 실행","Research summary":"연구 요약","Baseline":"기준 전략","Market":"시장","Research":"연구","Universe":"종목 범위","Daily bars":"일별 시세","Current identity":"현재 기업 식별","Open lifecycle cases":"미해결 종목 이력","Stock explorer":"종목 탐색","Qualified research models":"검증된 연구 모델","Research integrity":"연구 무결성","Open blockers":"미해결 차단 항목","Readiness":"준비 상태","Performance":"성과","Historical research":"과거 연구","Locked policy":"고정 정책","Verified":"검증 완료","In progress":"진행 중","Blocked":"차단","Not started":"시작 전","Validation":"검증","Research only":"연구 전용","Baseline executable":"기준 전략 실행 가능","Exchange calendar":"거래소 캘린더","Settlement":"결제","DART evidence":"DART 근거 자료","Security lifecycle":"종목 이력","Corporate actions":"기업행위","Run input freeze":"실행 입력값 고정","Historical backtest":"과거 백테스트","Market data":"시장 데이터","Qualified model":"검증된 모델","OOS evaluation":"표본외 평가","Complete":"완료","Mock research snapshot":"모의 연구 스냅샷","Approved KOSPI securities":"승인된 코스피 종목","Historical daily bars":"과거 일별 시세","Research inference artifact":"연구 추론 산출물","Frozen out-of-sample dataset":"고정된 표본외 데이터셋","Run not executed":"실행 전","Fail closed":"검증 전 차단","Freeze blocked":"고정 차단","Unresolved securities":"미해결 종목","Unexplained ticker-sessions":"설명되지 않은 종목·거래일","Historical identity coverage":"과거 종목 식별 범위","Run gate":"실행 조건","No historical results yet":"과거 실행 결과 없음","No fabricated performance metrics.":"임의의 성과 지표를 표시하지 않습니다.","View model details →":"모델 상세 보기 →","View evidence details →":"근거 자료 상세 보기 →","View baseline contract →":"기준 전략 계약 보기 →","Search stocks":"종목 검색","Ticker, company, or sector":"종목코드, 회사명 또는 업종","Clear search":"검색 초기화","records":"개 결과","No matching stock.":"일치하는 종목이 없습니다.","Try a ticker, company name, or available sector label.":"종목코드, 회사명 또는 업종으로 검색해 보세요.","Locked historical baseline":"고정된 과거 기준 전략","OHLC history":"OHLC 이력","Data contract":"데이터 계약","Historical coverage":"과거 데이터 범위","Quality and lifecycle":"품질 및 종목 이력","Data mode":"데이터 모드","Available from":"시작일","Latest coverage":"최근 데이터 기준일","Mock only":"모의 데이터 전용","Evidence limited":"근거 자료 제한","Mock stock detail":"모의 종목 상세","Stock research":"종목 연구","Total return":"총수익률","Max drawdown":"최대 낙폭","Win rate":"승률","Trades":"거래 횟수","← Back to stocks":"← 종목으로 돌아가기","← Back to models":"← 모델로 돌아가기","← Back to evidence":"← 근거 자료로 돌아가기","← Back to backtesting":"← 백테스트로 돌아가기","Baseline contract":"기준 전략 계약","Historical baseline":"과거 기준 전략","Run readiness":"실행 준비 상태","Pre-execution gates":"실행 전 조건","Not ready":"준비되지 않음","Chronology":"시간 순서","Immutable references":"변경 불가 참조","Artifact identity":"산출물 식별값","Model role":"모델 역할","Research qualification":"연구 적격성","Classification metrics":"분류 지표","Research inputs":"연구 입력값","Locked configuration":"고정 설정","Research only":"연구 전용",
"A research-first view of market data, model qualification, evidence readiness, and backtesting.":"시장 데이터, 모델 검증, 근거 자료 준비 상태 및 백테스트를 한눈에 확인합니다.",
"Historical baseline is intentionally locked.":"과거 기준 전략은 의도적으로 잠겨 있습니다.",
"Performance metrics will appear only after the run-input freeze is complete.":"실행 입력값 고정이 완료된 후 성과 지표가 표시됩니다.",
"Validation and frozen out-of-sample classification metrics are shown here. Backtest performance is intentionally excluded.":"검증 및 고정된 표본외 분류 지표를 표시합니다. 백테스트 성과는 제외합니다.",
"Source scope":"출처 범위","State":"상태","Verified findings":"검증된 결과","Evidence contract":"근거 자료 계약","Evidence fingerprint":"근거 자료 지문","Source and blocker state":"출처와 차단 상태","Selection":"선정","Contract":"계약","Dataset":"데이터셋","Samples":"표본 수","Feature set":"특징 집합","Decision threshold":"판단 임계값","Learning rate":"학습률","Max iterations":"최대 반복 횟수","Random seed":"난수 시드","On":"켜짐","Off":"꺼짐",
"Baseline policy":"기준 전략 정책","Official market-wide calendar verified":"공식 시장 캘린더 검증 완료","T+2 session mapping verified":"T+2 결제 거래일 매핑 검증 완료","Official disclosure evidence collected":"공식 공시 자료 수집 완료","43 securities still need historical lifecycle reconciliation":"43개 종목의 과거 이력 검증 필요","Complete historical coverage is not verified yet":"과거 전체 데이터 범위 검증 미완료","Waiting for remaining evidence blockers":"남은 근거 자료 차단 항목 해결 대기","No locked historical baseline has been executed":"고정된 과거 기준 전략은 아직 실행되지 않았습니다."
};
export function translate(locale: Locale, text: string): string { return locale === "ko" ? (ko[text] ?? text) : text; }
