import { isStockAnalysisSnapshot, type StockAnalysisSnapshot } from "../domain/stockAnalysis";

export type StockAnalysisMode = "disconnected" | "mock" | "http";
export interface StockAnalysisResult {
  source: StockAnalysisMode;
  data: StockAnalysisSnapshot;
  error: string | null;
}
export interface StockAnalysisOptions {
  mode?: string;
  apiBaseUrl?: string;
  fetcher?: typeof fetch;
}
export function demoStockAnalysis(ticker: string): StockAnalysisSnapshot {
  return {
    ticker,
    records: [
      { id: "demo-analysis-1", ticker, analyzedAt: "2026-10-01T18:30:00+09:00", dataThrough: "2026-10-01", modelId: "EXAMPLE-MODEL", modelVersion: "demo-v1", direction: "up", score: 0.72, validation: "pending", explanation: "Demonstration prediction only. Not generated by DonghakStockVision." },
      { id: "demo-analysis-2", ticker, analyzedAt: "2026-09-30T18:30:00+09:00", dataThrough: "2026-09-30", modelId: "EXAMPLE-MODEL", modelVersion: "demo-v1", direction: "neutral", score: null, validation: "blocked", explanation: "Demonstration prediction only. Not generated by DonghakStockVision." },
    ],
  };
}
export async function loadStockAnalysis(ticker: string, { mode = "disconnected", apiBaseUrl, fetcher = fetch }: StockAnalysisOptions = {}): Promise<StockAnalysisResult> {
  const empty: StockAnalysisSnapshot = { ticker, records: [] };
  if (mode === "disconnected") return { source: "disconnected", data: empty, error: null };
  if (mode === "mock") return { source: "mock", data: demoStockAnalysis(ticker), error: null };
  if (mode !== "http") return { source: "disconnected", data: empty, error: "Unsupported stock analysis mode" };
  if (!apiBaseUrl?.trim()) return { source: "http", data: empty, error: "Stock analysis API base URL is not configured" };
  try {
    const url = apiBaseUrl.trim().replace(/\\/+$/, "") + "/api/v1/stocks/" + encodeURIComponent(ticker) + "/analysis";
    const response = await fetcher(url, { headers: { Accept: "application/json" }, cache: "no-store", signal: AbortSignal.timeout(5000) });
    if (!response.ok) return { source: "http", data: empty, error: `Stock analysis API returned HTTP ${response.status}` };
    const body: unknown = await response.json();
    if (!isStockAnalysisSnapshot(body, ticker)) return { source: "http", data: empty, error: "Stock analysis API returned an invalid snapshot" };
    return { source: "http", data: body, error: null };
  } catch {
    return { source: "http", data: empty, error: "Stock analysis API is unreachable" };
  }
}
export function getStockAnalysis(ticker: string): Promise<StockAnalysisResult> {
  return loadStockAnalysis(ticker, { mode: process.env.MARKET_LENS_STOCK_ANALYSIS_SOURCE ?? "disconnected", apiBaseUrl: process.env.DONGHAK_API_BASE_URL });
}
